name: Videos Recientes de Youtube
on:
  schedule:
    # Se actualiza una vez al d√≠a 
    - cron: "0 16 * * 2"
  workflow_dispatch:

jobs:
  actualizar-readme-con-videos-nuevos:
    name: Actualizar este README con videos nuevos de Youtube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "VIDEOS-RECIENTES-YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCTMEgf6VREfyWOuRfu0xWlg"
